name: Build

on:
  push:
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'
    - run: npm ci

    - name: Build
      run: npm run build

    - name: Archive artifacts
      uses: actions/upload-artifact@v3
      with:
        name: lanting-app
        path: build/
