name: Storybook
on:
  push:
    branches:
      - master 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: latest
        cache: 'yarn'

    - run: yarn install --frozen-lockfile
    - run: npm run build-storybook
    - run: touch .nojekyll

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@3.6.2
      with:
        branch: gh-pages
        folder: storybook-static